[package]
name = "backend"
version = "0.8.4"
entry = "start.baga"
kind = "bin"

[dependencies]
fmrbaga = { path = "../../../app-product/fmrbaga" }
jwtbaga = { path = "../../../app-product/jwtbaga" }
ormbaga = { path = "../../../app-product/ormbaga" }
bagadecimal = { path = "../../../app-product/bagadecimal" }
chronobaga = { path = "../../../app-product/chronobaga" }
xmlbaga = { path = "../../../app-product/xmlbaga" }
reportbaga = { path = "../../../app-product/reportbaga" }
zipbaga = { path = "../../../app-product/zipbaga" }
std = { path = "../../../std" }
