[package]
name = "backend"
version = "0.1.0"
entry = "start.baga"
kind = "bin"

[dependencies]
fmrbaga = { path = "../../../app-product/fmrbaga" }
ormbaga = { path = "../../../app-product/ormbaga" }
bagadecimal = { path = "../../../app-product/bagadecimal" }
xmlbaga = { path = "../../../app-product/xmlbaga" }
reportbaga = { path = "../../../app-product/reportbaga" }
std = { path = "../../../std" }
